version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9002:9000'
      - '9001:9001'
    networks:
      - weather_data
    volumes:
      - 'minio_weather_data:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

  pgdatabase:
    image: postgres:13
    container_name: pgdatabase
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=weather_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - weather_data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - weather_data

networks:
  weather_data:
    driver: bridge

volumes:
  minio_weather_data:
  postgres_data: